spring.application.name=fitzonev2

spring.data.mongodb.database=fitzone_db
spring.data.mongodb.uri=mongodb://localhost:27017/fitzone_db


#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fitzonegym.oficial@gmail.com
spring.mail.password=drkqlqglulcaekak
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#nexu ohis tqqf upgd

jwt.secret=cf5d88c23a4e49c3b0e593fcd67e3c5e4a3e497fbffcb6a52906c7aa9b329b43e19437ad364c49b98f2e0ec42f6fbb24